const canvas = document.getElementById('ludoBoard');
const COLORS = [0xef6f61, 0x5f8ee8, 0x55af8e, 0xedb84e];
const NAMES = ['YOU', 'NOVA', 'MOSS', 'SOL'];
const STARTS = [0, 13, 26, 39];
const safeCells = new Set([0, 8, 13, 21, 26, 34, 39, 47]);
const state = { turn: 0, dice: 6, rolled: false, rolls: 0, streak: 0, best: Number(localStorage.getItem('ludo-best') || 0), winner: null, tokens: [[], [], [], []] };
const path = [], tokenMeshes = [], tokenTargets = [];
let scene, camera, renderer, raycaster, clock, socket, online = false, localBots = true, selectedMesh = null;
for (let x = 1; x <= 5; x++) path.push([x, 7]); for (let y = 6; y >= 1; y--) path.push([6, y]); for (let x = 7; x <= 13; x++) path.push([x, 1]); for (let y = 2; y <= 6; y++) path.push([14, y]); for (let x = 13; x >= 9; x--) path.push([x, 7]); for (let y = 8; y <= 13; y++) path.push([8, y]); for (let x = 7; x >= 1; x--) path.push([x, 13]); for (let y = 12; y >= 8; y--) path.push([1, y]);
const yards = [[[2.4,2.4],[4.1,2.4],[2.4,4.1],[4.1,4.1]],[[10.9,2.4],[12.6,2.4],[10.9,4.1],[12.6,4.1]],[[10.9,9.9],[12.6,9.9],[10.9,11.6],[12.6,11.6]],[[2.4,9.9],[4.1,9.9],[2.4,11.6],[4.1,11.6]]];
const homePaths = [1,2,3,4].map((_, i) => Array.from({length:5}, (_, j) => { const a=[[2,8],[8,2],[13,8],[8,13]][i]; return i===0?[a[0]+j,a[1]]:i===1?[a[0],a[1]+j]:i===2?[a[0]-j,a[1]]:[a[0],a[1]-j]; }));
function gridToWorld(x, y) { return [(x - 7.5) * 2.25, (y - 7.5) * 2.25]; }
function setup3D() { scene = new THREE.Scene(); scene.background = new THREE.Color(0xdfe9e4); scene.fog = new THREE.Fog(0xdfe9e4, 38, 70); camera = new THREE.PerspectiveCamera(42, 1, .1, 100); camera.position.set(0, 29, 27); camera.lookAt(0, 0, 0); renderer = new THREE.WebGLRenderer({ canvas, antialias:true, alpha:false }); renderer.setPixelRatio(Math.min(devicePixelRatio || 1, 2)); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap; renderer.outputColorSpace = THREE.SRGBColorSpace; raycaster = new THREE.Raycaster(); clock = new THREE.Clock(); scene.add(new THREE.HemisphereLight(0xffffff, 0x6e7d77, 2.1)); const sun = new THREE.DirectionalLight(0xfff0c9, 3); sun.position.set(-14, 28, 18); sun.castShadow = true; scene.add(sun); buildBoard(); resize(); }
function material(color, roughness=.6) { return new THREE.MeshStandardMaterial({ color, roughness, metalness:.08 }); }
function tile(x, y, color, yPos=.28) { const [wx,wz] = gridToWorld(x,y); const mesh = new THREE.Mesh(new THREE.BoxGeometry(2.1,.45,2.1), material(color)); mesh.position.set(wx,yPos,wz); mesh.castShadow = true; mesh.receiveShadow = true; scene.add(mesh); return mesh; }
function buildBoard() { const base = new THREE.Mesh(new THREE.BoxGeometry(34,1.1,34), material(0x263a42,.8)); base.position.y=-.55; base.receiveShadow=true; scene.add(base); const felt = new THREE.Mesh(new THREE.BoxGeometry(32,.28,32), material(0xf2f3ed)); felt.position.y=.05; felt.receiveShadow=true; scene.add(felt); [[0,0,COLORS[0]],[10,0,COLORS[1]],[10,10,COLORS[2]],[0,10,COLORS[3]]].forEach(([x,y,c])=>{const [wx,wz]=gridToWorld(x+3,y+3);const zone=new THREE.Mesh(new THREE.BoxGeometry(12.9,.22,12.9),material(c));zone.position.set(wx,.22,wz);scene.add(zone); const ring=new THREE.Mesh(new THREE.BoxGeometry(8.7,.18,8.7),material(0xfafaf4));ring.position.set(wx,.36,wz);scene.add(ring);}); for(let i=0;i<path.length;i++){const [x,y]=path[i];tile(x,y,safeCells.has(i)?0xf6d878:0xffffff,.35);} for(let i=0;i<4;i++)homePaths[i].forEach(([x,y])=>tile(x,y,COLORS[i],.37)); const center=new THREE.Mesh(new THREE.CylinderGeometry(6.1,6.1,.35,4),material(0xf9f5df)); center.rotation.y=Math.PI/4; center.position.y=.4; scene.add(center); }
function tokenPosition(player, token) { const progress=state.tokens[player][token]; if(progress===-1)return yards[player][token]; if(progress===56)return [7.5,7.5]; if(progress>51)return homePaths[player][progress-52]; return path[(STARTS[player]+progress-1+52)%52]; }
function createTokens() { tokenMeshes.length=0; for(let p=0;p<4;p++){tokenMeshes[p]=[]; for(let t=0;t<4;t++){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(.68,.8,.75,20),material(COLORS[p],.3));const cap=new THREE.Mesh(new THREE.SphereGeometry(.55,16,10),material(COLORS[p],.3));cap.position.y=.55;mesh.add(cap);mesh.userData={player:p,token:t};mesh.castShadow=true;scene.add(mesh);tokenMeshes[p].push(mesh);}} updateTokens(); }
function updateTokens() { for(let p=0;p<4;p++)for(let t=0;t<4;t++){const [x,y]=tokenPosition(p,t);const [wx,wz]=gridToWorld(x,y);const mesh=tokenMeshes[p][t];mesh.position.set(wx,1.15,wz);const movable=p===state.turn&&state.rolled&&movableTokens(p).includes(t);mesh.scale.setScalar(movable?1.2:1);mesh.material.emissive=new THREE.Color(movable?0x554433:0x000000);tokenTargets.push({mesh,x:wx,z:wz});} }
function resize(){if(!renderer)return;const box=canvas.getBoundingClientRect();renderer.setSize(Math.max(320,box.width),Math.max(320,box.height),false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix();} window.addEventListener('resize',resize);
function reset(){state.turn=0;state.dice=6;state.rolled=false;state.rolls=0;state.streak=0;state.winner=null;state.tokens=[0,1,2,3].map(()=>[-1,-1,-1,-1]);updateUI();updateTokens();}
function updateUI(){document.getElementById('turnName').textContent=NAMES[state.turn];document.getElementById('turnColor').textContent=['RED','BLUE','GREEN','YELLOW'][state.turn];document.getElementById('diceValue').textContent=state.dice;document.getElementById('rollCount').textContent=state.rolls;document.getElementById('bestScore').textContent=state.best;document.getElementById('streakValue').textContent=state.streak;document.getElementById('diceHint').textContent=state.rolled?'Choose a glowing token':'Roll the dice to begin';['red','blue','green','yellow'].forEach((n,i)=>document.getElementById(`${n}Home`).textContent=`${state.tokens[i].filter(v=>v===56).length}/4`);document.getElementById('totalHome').textContent=state.tokens[0].filter(v=>v===56).length;document.getElementById('saveStatus').textContent=online?'MULTIPLAYER CONNECTED':state.winner?`${NAMES[state.winner]} WINS / SAVED`:'LOCAL GAME';document.querySelector('.online-pill').innerHTML=online?'<i></i> ONLINE ROOM':'<i></i> LOCAL PLAY';}
function movableTokens(player){return state.tokens[player].map((value,index)=>value===-1?state.dice===6:value+state.dice<=56).map((can,index)=>can?index:-1).filter(index=>index>=0);}
function roll(){if(state.turn!==0||state.rolled||state.winner!==null)return;state.dice=Math.floor(Math.random()*6)+1;state.rolls++;state.rolled=true;state.streak=state.dice===6?state.streak+1:0;send({type:'ludo-roll',dice:state.dice});updateUI();updateTokens();if(!movableTokens(0).length)setTimeout(nextTurn,600);}
function moveToken(player,token,remote=false){const value=state.tokens[player][token];state.tokens[player][token]=value===-1?1:value+state.dice;const landed=(STARTS[player]+state.tokens[player][token]-1+52)%52;if(state.tokens[player][token]<56&&!safeCells.has(landed))state.tokens.forEach((tokens,op)=>{if(op!==player)tokens.forEach((other,i)=>{if(other>=0&&other<56&&(STARTS[op]+other-1+52)%52===landed)tokens[i]=-1;});});if(state.tokens[player].every(v=>v===56)){state.winner=player;if(player===0){state.best=Math.max(state.best,state.rolls);localStorage.setItem('ludo-best',state.best);}}state.rolled=false;send(remote?null:{type:'ludo-move',player,token});updateUI();updateTokens();if(state.winner!==null)return;if(state.dice===6){state.turn=player;updateUI();if(player!==0)setTimeout(botTurn,650);}else nextTurn();}
function nextTurn(){state.turn=(state.turn+1)%4;state.rolled=false;updateUI();updateTokens();if(state.turn!==0&&!online)setTimeout(botTurn,700);}
function botTurn(){if(state.turn===0||state.winner!==null)return;state.dice=Math.floor(Math.random()*6)+1;state.rolls++;state.rolled=true;const movable=movableTokens(state.turn);updateUI();updateTokens();if(movable.length)setTimeout(()=>moveToken(state.turn,movable[movable.length-1]),650);else setTimeout(nextTurn,650);}
function send(data){if(data&&socket&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(data));}
function connect(){try{socket=new WebSocket(`ws://${location.hostname||'localhost'}:8080`);socket.onopen=()=>{online=true;localBots=false;updateUI();send({type:'ludo-ready'});};socket.onclose=()=>{online=false;localBots=true;updateUI();};socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='ludo-roll'){state.dice=m.dice;state.rolls++;state.rolled=true;updateUI();updateTokens();}if(m.type==='ludo-move')moveToken(m.player,m.token,true);};}catch{updateUI();}}
canvas.addEventListener('click',e=>{if(state.turn!==0||!state.rolled)return;const box=canvas.getBoundingClientRect();const ndc=new THREE.Vector2(((e.clientX-box.left)/box.width)*2-1,-((e.clientY-box.top)/box.height)*2+1);raycaster.setFromCamera(ndc,camera);const hits=raycaster.intersectObjects(tokenMeshes[0],true);if(hits.length){let obj=hits[0].object;while(obj.parent&&obj.userData.token===undefined)obj=obj.parent;const token=obj.userData.token;if(movableTokens(0).includes(token))moveToken(0,token);}});
document.getElementById('rollButton').addEventListener('click',roll);document.getElementById('rollButtonText').addEventListener('click',roll);document.getElementById('newGameButton').addEventListener('click',reset);document.getElementById('rulesButton').addEventListener('click',()=>document.getElementById('rulesDialog').showModal());document.getElementById('closeRules').addEventListener('click',()=>document.getElementById('rulesDialog').close());document.getElementById('closeRulesButton').addEventListener('click',()=>document.getElementById('rulesDialog').close());
function animate(){requestAnimationFrame(animate);const delta=Math.min(.05,clock.getDelta());tokenMeshes.flat().forEach(mesh=>{mesh.rotation.y+=delta*.8;});camera.position.x=Math.sin(performance.now()*.00008)*2;camera.lookAt(0,0,0);renderer.render(scene,camera);} setup3D();createTokens();reset();connect();animate();
